vector_db:
  index_name: 'trading-bot'

embedding_model:
  provider: 'google'
  model_name: 'models/text-embedding-004'

llm:
  google:
    provider: 'google'
    model_name: 'gemini-1.5-pro'
  groq:
    provider: 'groq'
    model_name: 'deepseek-r1-distill-llama-70b'

retriever:
  top_k : 3
  score_threshold: 0.5

tools:
  tavily:
    max_results: 5

